# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('gender', models.CharField(choices=[('boys', 'BOYS'), ('girls', 'GIRLS'), ('mixed', 'MIXED')], max_length=15)),
                ('category', models.CharField(choices=[('dist', 'DISTRICT'), ('national', 'NATIONAL'), ('prov', 'PROVINCIAL')], max_length=15)),
            ],
        ),
    ]
