# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[('day', 'DAY'), ('boarding', 'BOARDING'), ('both', 'DAY & BOARDING')], default='None', max_length=15),
            preserve_default=False,
        ),
    ]
